apiVersion: v1
kind: ServiceAccount
metadata:
  name: pull-through-cache
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::643930694730:role/eks-pods-access-aws-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pull-through-cache
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pull-through-cache
subjects:
  - kind: ServiceAccount
    name: pull-through-cache
    namespace: default
roleRef:
  kind: ClusterRole
  name: pull-through-cache
  apiGroup: rbac.authorization.k8s.io