apiVersion: v1
kind: Service
metadata:
  name: pull-through-cache
  namespace: default
spec:
  selector:
    app: pull-through-cache
  ports:
  - port: 443
    targetPort: tls
    name: application
  - port: 80
    targetPort: metrics
    name: metrics
